package com.skcc.tutorial.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-23T01:50:52.161+09:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.skcc.com/tutorial/ws/", name = "OrderService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OrderService {

    @WebResult(name = "orderId", targetNamespace = "http://www.skcc.com/tutorial/ws/", partName = "orderId")
    @WebMethod
    public java.lang.String placeOrder(
        @WebParam(partName = "order", name = "order", targetNamespace = "http://www.skcc.com/tutorial/ws/")
        OrderType order
    );

    @WebResult(name = "order", targetNamespace = "http://www.skcc.com/tutorial/ws/", partName = "parameters")
    @WebMethod(action = "http://www.skcc.com/tutorial/ws/findOrder")
    public OrderType findOrder(
        @WebParam(partName = "orderId", name = "orderId", targetNamespace = "http://www.skcc.com/tutorial/ws/")
        java.lang.String orderId
    );
}
